---
version: "3.8"

services:
  ubuntu_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME:-alexzam}
    container_name: ${CONTAINER_NAME:-ansible}
    tty: true
    user: ${USERNAME:-alexzam}
    working_dir: /home/${USERNAME:-alexzam}/ansible
    volumes:
      - .:/home/${USERNAME:-alexzam}/ansible
    environment:
      - USERNAME=${USERNAME:-alexzam}

  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME:-alexzam}
    user: ${USERNAME:-alexzam}
    working_dir: /home/${USERNAME:-alexzam}/ansible
    volumes:
      - .:/home/${USERNAME:-alexzam}/ansible
    environment:
      - USERNAME=${USERNAME:-alexzam}
    command: ["bash", "-lc", "ansible-playbook --syntax-check local.yml"]
