---
services:
  ubuntu_dev:
    image: ansible-ubuntu_dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME:-alexzam}
        USER_ID: ${USER_ID:-1000}
    tty: true
    user: ${USERNAME:-alexzam}
    environment:
      - USER=${USERNAME:-alexzam}
      - HOME=/home/${USERNAME:-alexzam}
      - SKIP_TAGS=${SKIP_TAGS:-work}
    volumes:
      - .:/home/${USERNAME:-alexzam}/ansible
      - ${HOME}/.vault_pass.txt:/run/secrets/vault_pass:ro
