#!/usr/bin/env bash

# Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible=14.2.0-1ppa~noble

# pull ansible
# sudo ansible-pull -U https://github.com/alexiszamanidis/ansible.git
