- hosts: localhost
  connection: local
  become: true
  pre_tasks:
      - name: Update Apt
        become: true
        apt:
            force_apt_get: true
            update_cache: true
            state: present

  tasks:
      - include: tasks/git-setup.yml
      - include: tasks/core-setup.yml
      - include: tasks/zsh-setup.yml
      - include: tasks/brave.yml
      - include: tasks/dotfiles.yml
