- hosts: localhost
  vars:
      user: "{{ lookup('env', 'USER') }}"
      home: "{{ lookup('env', 'HOME') }}"
      source_key: "./.ssh/id_rsa"
      dest_key: "{{ home }}/.ssh/id_rsa"
      java_dir_path: "{{ home }}/java"
      work_projects_dir_path: "{{ home }}/work-projects"
      dotfiles_dir_path: "{{ home }}/dotfiles"
      fehbg_file_path: "{{ home }}/.fehbg"
      background_images_dir_path: "{{ home }}/personal-projects/background-images"
      core_packages:
          - "snapd"
          - "curl"
          - "wget"
          - "zip"
          - "trash-cli"
          - "preload"
          - "htop"
          - "tree"
          - "python"
          - "docker.io"
          - "tmux"
      productivity_tools:
          - "gimp"
          - "kitty"
          - "i3"
          - "i3blocks"
          - "rofi"
          - "compton"
          - "dunst"
          - "feh"
          - "flameshot"
      personal_projects_dir_path: "{{ home }}/personal-projects"
      personal_projects:
          - "vscode-git-worktrees"
          - "alexiszamanidis.github.io"
          - "2022"
          - "background-images"
          - "scraper"
          - "wheels"
      npm_packages:
          - "yarn"
          - "eslint"
          - "typescript-language-server"
          - "typescript"
          - "ts-node"
      oh_my_zsh_dir_path: "{{ home }}/.oh-my-zsh"
      oh_my_zsh_plugins_dir_path: "{{ home }}/.oh-my-zsh/custom/plugins"
      zsh_plugins:
          - {
                repo: "https://github.com/zsh-users/zsh-autosuggestions.git",
                dir: "zsh-autosuggestions",
            }
          - {
                repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git",
                dir: "zsh-syntax-highlighting",
            }
          - { repo: "https://github.com/agkozak/zsh-z.git", dir: "zsh-z" }
          - {
                repo: "https://github.com/alexiszamanidis/zsh-git-fzf.git",
                dir: "zsh-git-fzf",
            }
  pre_tasks:
      - name: Update Apt
        become: true
        apt:
            force_apt_get: true
            update_cache: true
            state: present
            cache_valid_time: 86400 # 1 day
        tags: &tags ["install", "core", "productivity-tools"]
  tasks:
      - import_tasks: tasks/git.yml
      - import_tasks: tasks/ssh.yml
      - import_tasks: tasks/core.yml
      - import_tasks: tasks/node.yml
      - import_tasks: tasks/npm-packages.yml
      - import_tasks: tasks/java.yml
      - import_tasks: tasks/fzf.yml
      - import_tasks: tasks/zsh.yml
      - import_tasks: tasks/personal-projects.yml
      - import_tasks: tasks/work-projects.yml
      - import_tasks: tasks/nvim.yml
      - import_tasks: tasks/nvim-packages.yml
      - import_tasks: tasks/fonts.yml
      - import_tasks: tasks/brave.yml
      - import_tasks: tasks/dotfiles.yml
      - import_tasks: tasks/productivity-tools.yml
      - import_tasks: tasks/background-images.yml
