---
- hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
        cache_valid_time: 86400 # 1 day
      tags: ["install", "core", "productivity-tools"]
  tasks:
    - ansible.builtin.import_tasks: tasks/git.yml
    - ansible.builtin.import_tasks: tasks/ssh.yml
    - ansible.builtin.import_tasks: tasks/core.yml
    - ansible.builtin.import_tasks: tasks/node.yml
    - ansible.builtin.import_tasks: tasks/npm-packages.yml
    - ansible.builtin.import_tasks: tasks/java.yml
    - ansible.builtin.import_tasks: tasks/fzf.yml
    - ansible.builtin.import_tasks: tasks/zsh.yml
    - ansible.builtin.import_tasks: tasks/personal-projects.yml
    - ansible.builtin.import_tasks: tasks/work.yml
    - ansible.builtin.import_tasks: tasks/nvim.yml
    - ansible.builtin.import_tasks: tasks/nvim-wsl.yml
      when: is_wsl == true
    - ansible.builtin.import_tasks: tasks/fonts.yml
    - ansible.builtin.import_tasks: tasks/brave.yml
      when: is_wsl == false
    - ansible.builtin.import_tasks: tasks/dotfiles.yml
    - ansible.builtin.import_tasks: tasks/productivity-tools.yml
      when: is_wsl == false
    - ansible.builtin.import_tasks: tasks/background-images.yml
      when: is_wsl == false
