- hosts: localhost
  vars:
      source_key: "./.ssh/id_rsa"
      dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
      java_dir_path: "{{ lookup('env', 'HOME') }}/java"
      work_projects_dir_path: "{{ lookup('env', 'HOME') }}/work-projects"
      personal_projects_dir_path: "{{ lookup('env', 'HOME') }}/personal-projects"
      dotfiles_dir_path: "{{ lookup('env', 'HOME') }}/dotfiles"
      personal_projects:
          - "vscode-git-worktrees"
          - "alexiszamanidis.github.io"
          - "2022"
      npm_packages:
          - "yarn"
          - "eslint"
          - "typescript-language-server"
          - "typescript"
          - "ts-node"
      oh_my_zsh_dir_path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
      oh_my_zsh_plugins_dir_path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins"
      zsh_plugins:
          - {
                repo: "https://github.com/zsh-users/zsh-autosuggestions.git",
                dir: "zsh-autosuggestions",
            }
          - {
                repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git",
                dir: "zsh-syntax-highlighting",
            }
          - { repo: "https://github.com/agkozak/zsh-z.git", dir: "zsh-z" }
          - {
                repo: "https://github.com/alexiszamanidis/zsh-git-fzf.git",
                dir: "zsh-git-fzf",
            }
  vars_prompt:
      - name: "unix_password"
        prompt: "Enter unix password"
        private: yes
  pre_tasks:
      - name: Update Apt
        become: true
        apt:
            force_apt_get: true
            update_cache: true
            state: present
        tags:
            - install
            - core
  tasks:
      - import_tasks: tasks/ssh.yml
      - import_tasks: tasks/git.yml
      - import_tasks: tasks/core.yml
      - import_tasks: tasks/node.yml
      - import_tasks: tasks/npm-packages.yml
      - import_tasks: tasks/java.yml
      - import_tasks: tasks/fzf.yml
      - import_tasks: tasks/zsh.yml
      - import_tasks: tasks/personal-projects.yml
      - import_tasks: tasks/work-projects.yml
      - import_tasks: tasks/nvim.yml
      - import_tasks: tasks/nvim-packages.yml
      - import_tasks: tasks/fonts.yml
      - import_tasks: tasks/brave.yml
      - import_tasks: tasks/dotfiles.yml
      - import_tasks: tasks/productivity-tools.yml
