---
- name: Check if AI agents repo exists
  ansible.builtin.stat:
    path: "{{ ai_agents_repo_path }}"
  register: ai_agents_repo_stats

- name: Clone ai-agents repo
  ansible.builtin.git:
    repo: git@github.com:alexiszamanidis/ai-agents.git
    dest: "{{ ai_agents_repo_path }}"
    recursive: true
    update: true
    accept_hostkey: true
    key_file: "{{ dest_key }}"
    version: master
  when: not ai_agents_repo_stats.stat.exists

- name: Run AI agents install script
  ansible.builtin.shell: |
    chmod +x install && ./install
  args:
    chdir: "{{ ai_agents_repo_path }}"
  register: ai_agents_install_result
  changed_when: false

- name: Show AI agents install stdout
  ansible.builtin.debug:
    msg: "{{ ai_agents_install_result.stdout_lines }}"
  when: ai_agents_install_result.stdout != ''

- name: Show AI agents install stderr
  ansible.builtin.debug:
    msg: "{{ ai_agents_install_result.stderr_lines }}"
  when: ai_agents_install_result.stderr != ''
