- name: If the OS is WSL, then don't continue
  meta: end_play
  tags: &tags ["install", "background-images"]
  when: is_wsl == true

- name: Check if .fehbg file exists
  stat:
      path: "{{ fehbg_file_path }}"
  register: fehbg_stats
  tags: *tags

- name: If .fehbg file exists, then don't continue the tasks
  meta: end_play
  tags: *tags
  when: fehbg_stats.stat.exists == true and fehbg_stats.stat.isdir == false

- name: Select random image
  shell: 'find "{{ background_images_dir_path }}" -maxdepth 2 -type f -not -path "{{ background_images_dir_path }}/.git/*"  | shuf -n 1'
  register: random_image
  tags: *tags

- name: Create .fehbg file
  template:
      src: .fehbg.j2
      dest: ~/.fehbg
      mode: u=rwx,g=rx,o=r
  tags: *tags

- name: Set background image
  shell: "{{ fehbg_file_path }}"
  tags: *tags
