- name: Install stow
  apt: name=stow
  tags:
      - install
      - dotfiles
- name: Clone dotfiles
  ansible.builtin.git:
      repo: "git@github.com:alexiszamanidis/dotfiles.git"
      dest: "{{ lookup('env', 'HOME') }}/dotfiles"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: main
  tags:
      - install
      - dotfiles
# TODO: remove all default files, folders that need to be stowed
- name: Remove default .zshrc
  shell: rm -rf ~/.zshrc
  tags:
      - install
      - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/dotfiles && chmod +x install stow unstow && ./install
  tags:
      - install
      - dotfiles
