- name: Install stow
  apt: name=stow
  tags: &tags ["install", "dotfiles"]

- name: Clone dotfiles
  ansible.builtin.git:
      repo: "git@github.com:alexiszamanidis/dotfiles.git"
      dest: "{{ lookup('env', 'HOME') }}/dotfiles"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: main
  tags: *tags

# TODO: remove all default files, folders that need to be stowed
- name: Remove default .zshrc
  shell: rm -rf ~/.zshrc
  tags: *tags

- name: Stow dotfiles
  shell: cd $HOME/dotfiles && chmod +x install stow unstow && ./install
  tags: *tags

# TODO need to change this file override. I need to add a user named 'alexzam' in the Docker
- name: Override ZSH path in .zshrc
  shell: sed -i "s/export ZSH=\"\/home\/alexzam\/.oh-my-zsh/export ZSH=\"\/root\/.oh-my-zsh/" ~/.zshrc
  tags:
      - docker-dotfiles
