---
- name: Install stow
  become: true
  ansible.builtin.apt:
    name: ["stow"]
  tags: &tags ["install", "dotfiles"]

- name: Check if dotfiles exist
  ansible.builtin.stat:
    path: "{{ dotfiles_dir_path }}"
  register: dotfiles_stats
  tags: *tags

- name: Clone dotfiles
  ansible.builtin.git:
    repo: "git@github.com:alexiszamanidis/dotfiles.git"
    dest: "{{ dotfiles_dir_path }}"
    recursive: true
    update: true
    accept_hostkey: true
    key_file: "{{ dest_key }}"
  # depth: 1
  # version: master
  tags: *tags
  when: dotfiles_stats.stat.exists == False

- name: Remove all default files/folders that need to be stowed (~/.zshrc)
  ansible.builtin.file:
    state: absent
    path: ~/.zshrc
  tags: *tags

- name: Stow dotfiles
  ansible.builtin.shell: cd $HOME/dotfiles && chmod +x install stow unstow && ./install
  tags: *tags

- name: Stow wsl
  ansible.builtin.shell: cd $HOME/dotfiles && chmod +x wsl && ./wsl
  when: is_wsl == True
  tags: *tags
