- name: Install stow
  become: true
  apt: name=stow
  tags: &tags ["install", "dotfiles"]

- name: Clone dotfiles
  ansible.builtin.git:
      repo: "git@github.com:alexiszamanidis/dotfiles.git"
      dest: "{{ lookup('env', 'HOME') }}/dotfiles"
      recursive: yes
      update: yes
      accept_hostkey: yes
      key_file: "{{ dest_key }}"
      version: master
  tags: *tags

# TODO: remove all default files, folders that need to be stowed
- name: Remove default .zshrc
  file:
      state: absent
      path: ~/.zshrc
  tags: *tags

- name: Stow dotfiles
  shell: cd $HOME/dotfiles && chmod +x install stow unstow && ./install
  tags: *tags
