- name: Install stow
  become: true
  apt: name=stow
  tags: &tags ["install", "dotfiles"]

- name: Check if dotfiles exist
  stat:
      path: "{{ dotfiles_dir_path }}"
  register: dotfiles_stats
  tags: *tags

- name: Clone dotfiles
  ansible.builtin.git:
      repo: "git@github.com:alexiszamanidis/dotfiles.git"
      dest: "{{ dotfiles_dir_path }}"
      recursive: yes
      update: yes
      accept_hostkey: yes
      key_file: "{{ dest_key }}"
      # version: master
  tags: *tags
  when: dotfiles_stats.stat.exists == False

- name: Remove all default files/folders that need to be stowed (~/.zshrc)
  file:
      state: absent
      path: ~/.zshrc
  tags: *tags

- name: Stow dotfiles
  shell: cd $HOME/dotfiles && chmod +x install stow unstow && ./install
  tags: *tags
