- name: Create fonts directory
  file:
      path: ~/.local/share/fonts
      state: directory
  tags: &tags ["install", "fonts"]

- name: Download Hack Italic fonts
  get_url:
      url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Italic/complete/Hack%20Italic%20Nerd%20Font%20Complete%20Mono.ttf
      dest: "~/.local/share/fonts/Hack Italic Nerd Font Complete Mono.ttf"
  tags: *tags

- name: Download Hack Bold fonts
  get_url:
      url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Bold/complete/Hack%20Bold%20Nerd%20Font%20Complete%20Mono.ttf
      dest: "~/.local/share/fonts/Hack Bold Nerd Font Complete Mono.ttf"
  tags: *tags

- name: Download Hack Bold Italic fonts
  get_url:
      url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/BoldItalic/complete/Hack%20Bold%20Italic%20Nerd%20Font%20Complete%20Mono.ttf
      dest: "~/.local/share/fonts/Hack Bold Italic Nerd Font Complete Mono.ttf"
  tags: *tags

- name: Download Hack Regular fonts
  get_url:
      url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete%20Mono.ttf
      dest: "~/.local/share/fonts/Hack Regular Nerd Font Complete Mono.ttf"
  tags: *tags

- name: Download fonts
  become: true
  shell: fc-cache -f -v
  tags: *tags
