- name: Create fonts directory
  file:
      path: "{{ fonts_dir_path }}"
      state: directory
  tags: &tags ["install", "fonts"]

- name: Download Nerd Fonts
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/{{ item.style }}/complete/{{ item.font_name | replace(' ', '%20') }}.ttf"
    dest: "{{ fonts_dir_path }}/{{ item.font_name }}.ttf"
  with_items: "{{ font_files }}"
  tags: *tags

- name: Update font cache
  become: true
  shell: fc-cache -f -v
  tags: *tags
