# dpkg, wget are in core-setup.yml but I added them here as well so I can be able to execute fzf.yml individually
- name: Install dpkg, wget
  become: true
  apt:
      name: ["dpkg", "wget"]
  tags:
      - install
      - fzf

- name: Install fzf
  become: true
  shell: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install
  tags:
      - install
      - fzf

- name: Install fd
  become: true
  shell: wget https://github.com/sharkdp/fd/releases/download/v7.3.0/fd-musl_7.3.0_amd64.deb && dpkg -i fd-musl_7.3.0_amd64.deb && rm -rf fd-musl_7.3.0_amd64.deb
  tags:
      - install
      - fzf

- name: Install bat
  become: true
  shell: wget https://github.com/sharkdp/bat/releases/download/v0.18.1/bat-musl_0.18.1_amd64.deb && dpkg -i bat-musl_0.18.1_amd64.deb && rm -rf bat-musl_0.18.1_amd64.deb
  tags:
      - install
      - fzf
