- name: Remove Git
  become: true
  package:
      name: ["git"]
      state: absent
  tags: &tags ["git"]

- name: Add git-core/ppa
  become: true
  # shell: add-apt-repository -y ppa:git-core/ppa
  apt_repository:
      repo: 'ppa:git-core/ppa'
      state: present
  tags: *tags

- name: Install git
  become: true
  apt:
      update_cache: yes
      name: ["git"]
  tags: *tags

# Personal
- name: Git personal setup email
  git_config:
      name: user.email
      scope: global
      value: "alexiszamanidis@outlook.com"
  tags:
      - git-personal

- name: Git personal setup name
  git_config:
      name: user.name
      scope: global
      value: "alexiszamanidis"
  tags:
      - git-personal

# Work
- name: Git work setup email
  git_config:
      name: user.email
      scope: global
      value: "Alexis.Zamanidis@Openbet.com"
  tags:
      - git-work

- name: Git work setup name
  git_config:
      name: user.name
      scope: global
      value: "alexis.zamanidis"
  tags:
      - git-work
