# TODO: Let's fix this antipattern
# Don't use shell. Instead find a way to compare package versions
- name: Get Git Version
  shell: git --version | awk -v x=3 '{print $x}'
  register: git_version
  tags: &tags ["install", "git"]

- name: If git version >= 2.38.1, then don't continue the tasks
  meta: end_play
  tags: *tags
  when: git_version.stdout >= "2.38.1"

- name: Remove Git
  become: true
  package:
      name: ["git"]
      state: absent
  tags: *tags

- name: Add git-core/ppa
  become: true
  apt_repository:
      repo: 'ppa:git-core/ppa'
      state: present
  tags: *tags

- name: Install git
  become: true
  apt:
      update_cache: yes
      name: ["git"]
  tags: *tags

# Personal
- name: Git personal setup email
  git_config:
      name: user.email
      scope: global
      value: "alexiszamanidis@outlook.com"
  tags:
      - git-personal

- name: Git personal setup name
  git_config:
      name: user.name
      scope: global
      value: "alexiszamanidis"
  tags:
      - git-personal

# Work
- name: Git work setup email
  git_config:
      name: user.email
      scope: global
      value: "Alexis.Zamanidis@Openbet.com"
  tags:
      - git-work

- name: Git work setup name
  git_config:
      name: user.name
      scope: global
      value: "alexis.zamanidis"
  tags:
      - git-work
