- name: Install default-jre
  become: true
  apt:
      name: ["default-jre"]
  tags: &tags ["install", "java"]

- name: Install java 17(Required for the packages below)
  become: true
  apt:
      name: ["openjdk-17-jdk", "openjdk-17-jre"]
  tags: *tags

- name: Download and Install sdkman
  shell: curl -s https://get.sdkman.io | bash
  tags: *tags

# TODO: Should fix this!
# - name: Install java via sdk
#   shell: sdk install java
#   tags: *tags

- name: Create java directory
  file:
      path: "{{ java_dir_path }}"
      state: directory
  tags: *tags

- name: "Create {{ java_dir_path }}/jdt-language-server/workspace/folder directory"
  file:
      path: "{{ java_dir_path }}/jdt-language-server/workspace/folder"
      state: directory
  tags: *tags

- name: Check that the jdt-language-server exists
  stat:
      path: "{{ java_dir_path }}/jdt-language-server/jdt-language-server-1.9.0-202203031534.tar.gz"
  register: jdt_language_server_exists
  tags: *tags

- name: Download jdt-language-server
  get_url:
      url: https://download.eclipse.org/jdtls/milestones/1.9.0/jdt-language-server-1.9.0-202203031534.tar.gz
      dest: "{{ java_dir_path }}/jdt-language-server"
  when: jdt_language_server_exists.stat.exists == False
  tags: *tags

- name: Extract jdt-language-server
  shell: "cd {{ java_dir_path }}/jdt-language-server && tar -zxvf jdt-language-server-1.9.0-202203031534.tar.gz"
  tags: *tags

- name: Check that the lombok exists
  stat:
      path: "{{ java_dir_path }}/jdt-language-server/lombok.jar"
  register: lombok_exists
  tags: *tags

- name: Download lombok
  get_url:
      url: https://projectlombok.org/downloads/lombok.jar
      dest: "{{ java_dir_path }}/jdt-language-server"
  when: lombok_exists.stat.exists == False
  tags: *tags

- name: Check that the java-debug exists
  stat:
      path: "{{ java_dir_path }}/java-debug"
  register: java_debug_exists
  tags: *tags

- name: Clone java-debug
  ansible.builtin.git:
      repo: "https://github.com/microsoft/java-debug.git"
      dest: "{{ java_dir_path }}/java-debug"
      recursive: yes
      update: yes
      depth: 1
  when: java_debug_exists.stat.exists == False
  tags: *tags

- name: Install java-debug
  shell: "cd {{ java_dir_path }}/java-debug && ./mvnw clean install"
  tags: *tags
  
- name: Check that the vscode-java-test exists
  stat:
      path: "{{ java_dir_path }}/vscode-java-test"
  register: vscode_java_test_exists
  tags: *tags

- name: Clone vscode-java-test
  ansible.builtin.git:
      repo: "https://github.com/microsoft/vscode-java-test.git"
      dest: "{{ java_dir_path }}/vscode-java-test"
      recursive: yes
      update: yes
      depth: 1
  when: vscode_java_test_exists.stat.exists == False
  tags: *tags

- name: Install vscode-java-test
  shell: "cd {{ java_dir_path }}/vscode-java-test && npm install && npm run build-plugin"
  tags: *tags
