---
- name: Install default-jre
  become: true
  ansible.builtin.apt:
    name: [default-jre]

- name: Install java 17(Required for the packages below)
  become: true
  ansible.builtin.apt:
    name: [openjdk-17-jdk, openjdk-17-jre]

- name: Download sdkman
  ansible.builtin.get_url:
    url: https://get.sdkman.io
    dest: /tmp/sdkman_installer.sh
    mode: "0644"

- name: Install sdkman
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      /tmp/sdkman_installer.sh | bash
  changed_when: false

# TODO: Should fix this!
# - name: Install java via sdk
#   shell: sdk install java

- name: Create java directory
  ansible.builtin.file:
    path: "{{ java_dir_path }}"
    state: directory
    mode: "0755"

- name: Create jdt-language-server/workspace/folder directory
  ansible.builtin.file:
    path: "{{ java_dir_path }}/jdt-language-server/workspace/folder"
    state: directory
    mode: "0755"

- name: Check that the jdt-language-server exists
  ansible.builtin.stat:
    path: "{{ java_dir_path }}/jdt-language-server/jdt-language-server-1.9.0-202203031534.tar.gz"
  register: jdt_language_server_exists

- name: Download jdt-language-server
  ansible.builtin.get_url:
    url: https://download.eclipse.org/jdtls/milestones/1.9.0/jdt-language-server-1.9.0-202203031534.tar.gz
    dest: "{{ java_dir_path }}/jdt-language-server"
    mode: "0755"
  when: not jdt_language_server_exists.stat.exists

- name: Extract jdt-language-server
  ansible.builtin.shell: cd {{ java_dir_path }}/jdt-language-server && tar -zxvf jdt-language-server-1.9.0-202203031534.tar.gz
  changed_when: false

- name: Check that the lombok exists
  ansible.builtin.stat:
    path: "{{ java_dir_path }}/jdt-language-server/lombok.jar"
  register: lombok_exists

- name: Download lombok
  ansible.builtin.get_url:
    url: https://projectlombok.org/downloads/lombok.jar
    dest: "{{ java_dir_path }}/jdt-language-server"
    mode: "0755"
  when: not lombok_exists.stat.exists

- name: Check that the java-debug exists
  ansible.builtin.stat:
    path: "{{ java_dir_path }}/java-debug"
  register: java_debug_exists

- name: Clone java-debug
  ansible.builtin.git:
    repo: https://github.com/microsoft/java-debug.git
    dest: "{{ java_dir_path }}/java-debug"
    recursive: true
    update: true
    depth: 1
    version: master
  when: not java_debug_exists.stat.exists

- name: Install java-debug
  ansible.builtin.shell: cd {{ java_dir_path }}/java-debug && ./mvnw clean install
  changed_when: false

- name: Check that the vscode-java-test exists
  ansible.builtin.stat:
    path: "{{ java_dir_path }}/vscode-java-test"
  register: vscode_java_test_exists

- name: Clone vscode-java-test
  ansible.builtin.git:
    repo: https://github.com/microsoft/vscode-java-test.git
    dest: "{{ java_dir_path }}/vscode-java-test"
    recursive: true
    update: true
    depth: 1
    version: master
  when: not vscode_java_test_exists.stat.exists

- name: Install vscode-java-test
  ansible.builtin.shell: cd {{ java_dir_path }}/vscode-java-test && npm install && npm run build-plugin
  changed_when: false
