- name: Install nodejs and npm
  become: true
  apt:
      name: ["nodejs", "npm"]
  tags:
      - install
      - node

- name: Create .np,-global
  shell: mkdir -p ~/.local/.npm-global
  tags:
      - install
      - node

- name: Add npm to path
  shell: PATH=~/.local/.npm-global/bin:$PATH
  tags:
      - install
      - node

- name: npm global settings
  shell: npm config set prefix '~/.local/.npm-global'
  tags:
      - install
      - node

- name: Install N
  npm:
      name: n
      global: yes
  tags:
      - install
      - node

- name: Install version 14 of Node
  shell: n 14
  tags:
      - install
      - node
