- name: Install nodejs and npm
  become: true
  apt:
      name: ["nodejs", "npm"]
  tags: &tags ["install", "node"]

- name: Create .npm-global directory
  file:
      path: ~/.local/.npm-global
      state: directory
  tags: *tags

- name: Add npm to path
  shell: PATH=~/.local/.npm-global/bin:$PATH
  tags: *tags

- name: npm global settings
  shell: npm config set prefix '~/.local/.npm-global'
  tags: *tags

- name: Download nvm
  get_url:
      url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
      dest: ~/.nvm-installer
      mode: a+x
  tags: *tags

- name: Install nvm
  shell: ~/.nvm-installer && rm -rf ~/.nvm-installer
  tags: *tags
# TODO: Should fix this!
# - name: Install version 16 of Node
#   shell: source ~/.bashrc && nvm install 16.16.0 && nvm alias default 16.16.0 && nvm use 16.16.0
#   tags: *tags
