- name: Install nodejs and npm
  become: true
  apt:
      name: ["nodejs", "npm"]
  tags: &tags ["install", "node"]

- name: Create .np,-global
  shell: mkdir -p ~/.local/.npm-global
  tags: *tags

- name: Add npm to path
  shell: PATH=~/.local/.npm-global/bin:$PATH
  tags: *tags

- name: npm global settings
  shell: npm config set prefix '~/.local/.npm-global'
  tags: *tags

- name: Install N
  npm:
      name: n
      global: yes
  tags: *tags
# TODO: fix this
# - name: Install version 14 of Node
#   shell: n 14
#   tags: *tags
