- name: Add neovim-ppa
  become: true
  shell: add-apt-repository -y ppa:neovim-ppa/unstable
  tags: &tags ["install", "nvim"]

- name: Install neovim
  become: true
  apt:
      name: ["neovim"]
  tags: *tags

- name: Install neovim prerequisites(xclip, ripgrep)
  become: true
  apt:
      name: ["xclip", "ripgrep"]
  tags: *tags
