---
- name: Add neovim-ppa
  become: true
  ansible.builtin.command: add-apt-repository -y ppa:neovim-ppa/unstable
  changed_when: false

- name: Install neovim
  become: true
  ansible.builtin.apt:
    name: [neovim]

- name: Install neovim prerequisites(xclip, ripgrep)
  become: true
  ansible.builtin.apt:
    name: [xclip, ripgrep]
