- name: Install neovim
  become: true
  apt:
      name: ["neovim"]
  tags: &tags ["install", "nvim"]

- name: Download plug.vim for neovim
  shell: curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags: *tags

- name: Install neovim plugins
  shell: nvim +'PlugInstall --sync' +qa
  tags: *tags
