- name: Install prerequisite packages
  become: true
  apt:
      name: ["cargo", "pip"]
  tags: &tags ["install", "nvim-packages", "nvim"]

- name: (null-ls) - Install stylua
  community.general.cargo:
      name: stylua
  tags: *tags

- name: (null-ls) - Install codespell and beautysh
  ansible.builtin.pip:
      name: ["codespell", "beautysh"]
  tags: *tags

- name: (null-ls) Install Google-Java-Format
  npm:
      name: google-java-format
      global: yes
  tags: *tags
