- name: Add neovim-ppa
  become: true
  shell: add-apt-repository -y ppa:neovim-ppa/unstable
  tags: &tags ["install", "nvim"]

- name: Install neovim
  become: true
  apt:
      name: ["neovim"]
  tags: *tags

- name: Install neovim prerequisites(xclip, ripgrep)
  become: true
  apt:
      name: ["xclip", "ripgrep"]
  tags: *tags

- name: Check that win32yank.exe exists
  stat:
      path: "{{ bin_dir_path }}/win32yank.exe"
  register: win32yank_stats
  tags: [*tags, "win32yank", "wsl"]

- name: Download win32yank.exe
  shell: curl -sLo/tmp/win32yank.zip https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
  when: win32yank_stats.stat.exists == False
  tags: [*tags, "win32yank", "wsl"]

- name: Unzip win32yank.exe
  shell: unzip -p /tmp/win32yank.zip win32yank.exe > /tmp/win32yank.exe
  when: win32yank_stats.stat.exists == False
  tags: [*tags, "win32yank", "wsl"]

- name: Setup win32yank.exe
  shell: "chmod +x /tmp/win32yank.exe && mv /tmp/win32yank.exe {{ bin_dir_path }}/fd"
  when: win32yank_stats.stat.exists == False
  tags: [*tags, "win32yank", "wsl"]
