- name: Create personal directory
  file:
      path: "{{ personal }}"
      state: directory
  tags: &tags ["install", "personal-projects"]

- name: Clone zsh-git-fzf
  ansible.builtin.git:
      repo: "git@github.com:alexiszamanidis/zsh-git-fzf.git"
      dest: "{{ personal }}/zsh-git-fzf"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: main
  tags: *tags

- name: Clone alexiszamanidis.github.io
  ansible.builtin.git:
      repo: "git@github.com:alexiszamanidis/alexiszamanidis.github.io.git"
      dest: "{{ personal }}/alexiszamanidis.github.io"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: master
  tags: *tags

- name: Clone 2022
  ansible.builtin.git:
      repo: "git@github.com:alexiszamanidis/2022.git"
      dest: "{{ personal }}/2022"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: master
  tags: *tags
