- name: Install Packages (kitty, i3, rofi, compton, compton, i3blocks, feh)
  become: true
  apt:
      name: ["kitty", "i3", "rofi", "compton", "compton", "i3blocks", "feh"]
  tags: &tags ["install", "productivity-tools"]
