- name: Install Packages (gimp, kitty, i3, rofi, compton, dunst, i3blocks, feh)
  become: true
  apt:
      name:
          ["gimp", "kitty", "i3", "rofi", "compton", "dunst", "i3blocks", "feh"]
  tags: &tags ["install", "productivity-tools"]
