- name: Ensure .ssh directory exists
  file:
      dest: "{{ dest_key | dirname }}"
      mode: 0700
      state: directory
  tags: &tags ["install", "ssh"]

- name: Install ssh key
  copy:
      src: "{{ source_key }}"
      dest: "{{ dest_key }}"
      mode: 0600
  tags: *tags

- name: Install ssh key public
  copy:
      src: "{{ source_key }}.pub"
      dest: "{{ dest_key }}.pub"
      mode: 0644
  tags: *tags

- name: Set authorized key took from file
  authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ home }}/.ssh/id_rsa.pub"
  with_fileglob:
      - "{{ home }}/.ssh/*.pub"
