---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    dest: "{{ dest_key | dirname }}"
    mode: "0700"
    state: directory

- name: Install ssh key
  ansible.builtin.copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: "0600"

- name: Install ssh key public
  ansible.builtin.copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: "0644"

- name: Set authorized key took from file
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ home }}/.ssh/id_rsa.pub"
  with_fileglob:
    - "{{ home }}/.ssh/*.pub"
