---
- name: Check if ansible-work role exists
  ansible.builtin.stat:
    path: "{{ ansible_work_repo_path }}/tasks/main.yml"
  register: ansible_work_role

- name: Run ansible-work role if it exists
  ansible.builtin.include_role:
    name: "{{ ansible_work_repo_path }}"
  when: ansible_work_role.stat.exists
