---
- name: Install ZSH
  become: true
  ansible.builtin.apt:
    name: [zsh]

- name: Enter unix password
  ansible.builtin.pause:
    prompt: Enter unix password
    echo: false
  register: unix_password

- name: Change shell and set zsh as default
  ansible.builtin.expect:
    command: chsh -s /usr/bin/zsh
    responses:
      (?i)password: "{{ unix_password.user_input }}"
    creates: .shell_is_zsh

- name: Ensure zinit directory exists
  ansible.builtin.file:
    path: "{{ zinit_dir_path }}"
    state: directory
    mode: "0755"

- name: Install zinit
  ansible.builtin.git:
    repo: https://github.com/zdharma-continuum/zinit.git
    dest: "{{ zinit_home }}"
    depth: 1
    update: true
    version: main

- name: Ensure local bin directory exists
  ansible.builtin.file:
    path: "{{ bin_dir_path }}"
    state: directory
    mode: "0755"

- name: Check if starship is installed
  ansible.builtin.stat:
    path: "{{ bin_dir_path }}/starship"
  register: starship_stat

- name: Download starship installer
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship-install.sh
    mode: "0755"
  when: not starship_stat.stat.exists

- name: Install starship
  ansible.builtin.command:
    cmd: /tmp/starship-install.sh -y -b {{ bin_dir_path }}
    creates: "{{ bin_dir_path }}/starship"
  when: not starship_stat.stat.exists
