- name: Install ZSH
  become: true
  apt: name=zsh
  tags: &tags ["install", "dotfiles", "zsh"]

- name: Change shell and set zsh as default
  expect:
      command: "chsh -s /usr/bin/zsh"
      responses:
          (?i)password: "{{ unix_password }}"
      creates: ".shell_is_zsh"
  tags: *tags

- name: Check that the somefile.conf exists
  stat:
      path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_stats
  tags: *tags

- name: Download Oh-My-Zsh script
  get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: ~/.oh-my-zsh-installer
      mode: a+x
  tags: *tags
  when: oh_my_stats.stat.exists == False

- name: Install Oh-My-Zsh
  shell: ~/.oh-my-zsh-installer && rm -rf ~/.oh-my-zsh-installer
  tags: *tags
  when: oh_my_stats.stat.exists == False

- name: Install zsh-autosuggestions
  ansible.builtin.git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
      dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  tags: *tags

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  tags: *tags

- name: Install zsh-z
  ansible.builtin.git:
      repo: "https://github.com/agkozak/zsh-z.git"
      dest: "~/.oh-my-zsh/custom/plugins/zsh-z"
  tags: *tags

- name: Install zsh-git-fzf
  ansible.builtin.git:
      repo: "https://github.com/alexiszamanidis/zsh-git-fzf.git"
      dest: "~/.oh-my-zsh/custom/plugins/zsh-git-fzf"
  tags: *tags
