name: "Ansible-Lint"

on: ["pull_request", "push"]
jobs:
    ansible-lint:
        runs-on: ubuntu-latest
        steps:
            - name: check code out from github and into "ubuntu-latest" (or our environment)
              uses: actions/checkout@v4
            - uses: actions/setup-python@v2
            - run: pip install ansible ansible-lint
            - run: ansible-lint --version
            - run: ansible-lint .
