---
name: ci

on: [pull_request, push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Format files
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "feat(format): apply formatting changes"
          branch: ${{ github.head_ref }}

  lint:
    runs-on: ubuntu-latest
    needs: [format]
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible and ansible-lint
        run: |
          pip install ansible ansible-lint==25.5.0

      - name: Write Ansible Vault password to file
        run: echo "${{ secrets.VAULT_PASSWORD }}" > /home/runner/.vault_pass.txt
        shell: bash

      - name: Install Ansible Galaxy collections (globally)
        run: |
          ansible-galaxy collection install ansible.posix community.general

      - name: Lint Ansible playbook
        uses: ansible/ansible-lint@v25.5.0
        with:
          args: --fix -c ./.ansible-lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "feat(lint): apply linting changes"
          branch: ${{ github.head_ref }}
