---
name: ci

on: [pull_request, push]
jobs:
  format:
    uses: alexiszamanidis/.github/.github/workflows/prettier.yml@master
    permissions:
      contents: write

  lint:
    needs: [format]
    uses: alexiszamanidis/.github/.github/workflows/ansible-lint.yml@master
    permissions:
      contents: write
    secrets:
      VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
    with:
      use-vault: true
      install-galaxy: true
